### ISSUE TITLE
创建404页面与500页面

### ISSUE THREAD

**Issue by panmingzhi815** [panmingzhi815/simpleJavaWeb#1]
当访问系统页面时，页面如果未找到，则会跳到404页面。 参考页：http://www.oschina.net/question/88361_21953?sort=time
当访问系统页面时，页面中的代码发生错误，则会跳到500页面。参考页：http://www.zcool.com.cn/work/ZMTUwOTQ0OA==.html

你可以试着参考这些例示。

**Comment by imnot2** [comment]
haha~
